name: background_eraser
description: "Background Eraser - AI-powered background removal app for Flutter."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dio: ^5.9.0
  path: ^1.9.0
  uuid: ^4.3.3
  drift: ^2.14.1
  get_it: ^9.2.0
  equatable: ^2.0.8
  go_router: ^17.0.1
  flutter_bloc: ^9.1.1
  image_picker: ^1.2.1
  path_provider: ^2.1.2
  talker_flutter: ^5.1.9
  talker_dio_logger: ^5.1.9
  talker_bloc_logger: ^5.1.9
  permission_handler: ^12.0.1
  sqlite3_flutter_libs: ^0.5.18
  liquid_glass_renderer: ^0.2.0-dev.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  drift_dev: ^2.14.1
  build_runner: ^2.4.7

flutter:
  uses-material-design: true

  assets:
    - assets/png/
    - assets/fonts/
    - assets/icon_app/

  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik-Medium.ttf
          weight: 500
